[2024-09-25T11:12:56.566+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T11:12:56.676+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.pipeline.warehouse.step_2.load.orderlines manual__2024-09-25T11:05:57.968197+00:00 [queued]>
[2024-09-25T11:12:56.724+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.pipeline.warehouse.step_2.load.orderlines manual__2024-09-25T11:05:57.968197+00:00 [queued]>
[2024-09-25T11:12:56.725+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-25T11:12:56.784+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): pipeline.warehouse.step_2.load.orderlines> on 2024-09-25 11:05:57.968197+00:00
[2024-09-25T11:12:56.812+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1039) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T11:12:56.816+0000] {standard_task_runner.py:72} INFO - Started process 1057 to run task
[2024-09-25T11:12:56.842+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'pipeline.warehouse.step_2.load.orderlines', 'manual__2024-09-25T11:05:57.968197+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline/run.py', '--cfg-path', '/tmp/tmp8xc7v0nt']
[2024-09-25T11:12:56.885+0000] {standard_task_runner.py:105} INFO - Job 255: Subtask pipeline.warehouse.step_2.load.orderlines
[2024-09-25T11:12:57.078+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.pipeline.warehouse.step_2.load.orderlines manual__2024-09-25T11:05:57.968197+00:00 [running]> on host e10075799413
[2024-09-25T11:12:57.481+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='pipeline.warehouse.step_2.load.orderlines' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T11:05:57.968197+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T11:05:57.968197+00:00'
[2024-09-25T11:12:57.484+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T11:12:57.522+0000] {base.py:84} INFO - Retrieving connection 'minio'
[2024-09-25T11:12:58.270+0000] {base.py:84} INFO - Retrieving connection 'warehouse_db'
[2024-09-25T11:13:22.364+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-25T11:13:22.392+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T11:13:22.393+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=pipeline.warehouse.step_2.load.orderlines, run_id=manual__2024-09-25T11:05:57.968197+00:00, execution_date=20240925T110557, start_date=20240925T111256, end_date=20240925T111322
[2024-09-25T11:13:22.488+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-25T11:13:22.512+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
