[2024-10-04T06:36:50.007+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-04T06:36:50.084+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.staging.dellstore_db.extract.orderlines scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T06:36:50.152+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.staging.dellstore_db.extract.orderlines scheduled__2024-10-03T00:00:00+00:00 [queued]>
[2024-10-04T06:36:50.159+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-04T06:36:50.273+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): staging.dellstore_db.extract.orderlines> on 2024-10-03 00:00:00+00:00
[2024-10-04T06:36:50.308+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=203) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T06:36:50.308+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'staging.dellstore_db.extract.orderlines', 'scheduled__2024-10-03T00:00:00+00:00', '--job-id', '13693', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline/run.py', '--cfg-path', '/tmp/tmplzpl1kbu']
[2024-10-04T06:36:50.339+0000] {standard_task_runner.py:105} INFO - Job 13693: Subtask staging.dellstore_db.extract.orderlines
[2024-10-04T06:36:50.341+0000] {standard_task_runner.py:72} INFO - Started process 303 to run task
[2024-10-04T06:36:50.714+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.staging.dellstore_db.extract.orderlines scheduled__2024-10-03T00:00:00+00:00 [running]> on host 5f5bf3f98309
[2024-10-04T06:36:51.330+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='staging.dellstore_db.extract.orderlines' AIRFLOW_CTX_EXECUTION_DATE='2024-10-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-03T00:00:00+00:00'
[2024-10-04T06:36:51.334+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-04T06:36:51.397+0000] {base.py:84} INFO - Retrieving connection 'dellstore_db'
[2024-10-04T06:36:52.403+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 59, in _dellstore_db
    CustomMinio._put_csv(df, bucket_name, object_name)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'CustomMinio' has no attribute '_put_csv'. Did you mean: '_put_json'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 64, in _dellstore_db
    raise AirflowException(f"Error when extracting {table_name} : {str(e)}")
airflow.exceptions.AirflowException: Error when extracting orderlines : type object 'CustomMinio' has no attribute '_put_csv'
[2024-10-04T06:36:52.451+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=staging.dellstore_db.extract.orderlines, run_id=scheduled__2024-10-03T00:00:00+00:00, execution_date=20241003T000000, start_date=20241004T063650, end_date=20241004T063652
[2024-10-04T06:36:52.452+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: slack_notifier
[2024-10-04T06:36:52.460+0000] {baseoperator.py:405} WARNING - SlackWebhookOperator.execute cannot be called outside TaskInstance!
[2024-10-04T06:36:52.480+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/slack/hooks/slack_webhook.py:42 UserWarning: You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration. See: https://api.slack.com/messaging/webhooks#advanced_message_formatting. It is possible to change this values only in Legacy Slack Integration Incoming Webhook: https://api.slack.com/legacy/custom-integrations/messaging/webhooks#legacy-customizations
[2024-10-04T06:36:52.513+0000] {base.py:84} INFO - Retrieving connection 'slack_notifier'
[2024-10-04T06:36:53.123+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-04T06:36:53.124+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13693 for task staging.dellstore_db.extract.orderlines (Error when extracting orderlines : type object 'CustomMinio' has no attribute '_put_csv'; 303)
Traceback (most recent call last):
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 59, in _dellstore_db
    CustomMinio._put_csv(df, bucket_name, object_name)
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'CustomMinio' has no attribute '_put_csv'. Did you mean: '_put_json'?

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_pipeline/tasks/staging/components/extract.py", line 64, in _dellstore_db
    raise AirflowException(f"Error when extracting {table_name} : {str(e)}")
airflow.exceptions.AirflowException: Error when extracting orderlines : type object 'CustomMinio' has no attribute '_put_csv'
[2024-10-04T06:36:53.198+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-04T06:36:53.227+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
