[2024-09-25T11:07:52.236+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T11:07:52.303+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.pipeline.warehouse.step_2.load.orderlines manual__2024-09-25T11:02:00.229060+00:00 [queued]>
[2024-09-25T11:07:52.352+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.pipeline.warehouse.step_2.load.orderlines manual__2024-09-25T11:02:00.229060+00:00 [queued]>
[2024-09-25T11:07:52.354+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-25T11:07:52.456+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): pipeline.warehouse.step_2.load.orderlines> on 2024-09-25 11:02:00.229060+00:00
[2024-09-25T11:07:52.496+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=572) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T11:07:52.501+0000] {standard_task_runner.py:72} INFO - Started process 579 to run task
[2024-09-25T11:07:52.536+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'pipeline.warehouse.step_2.load.orderlines', 'manual__2024-09-25T11:02:00.229060+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline/run.py', '--cfg-path', '/tmp/tmp3yvj03yj']
[2024-09-25T11:07:52.563+0000] {standard_task_runner.py:105} INFO - Job 150: Subtask pipeline.warehouse.step_2.load.orderlines
[2024-09-25T11:07:52.833+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.pipeline.warehouse.step_2.load.orderlines manual__2024-09-25T11:02:00.229060+00:00 [running]> on host e10075799413
[2024-09-25T11:07:53.190+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='pipeline.warehouse.step_2.load.orderlines' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T11:02:00.229060+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T11:02:00.229060+00:00'
[2024-09-25T11:07:53.192+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T11:07:53.251+0000] {base.py:84} INFO - Retrieving connection 'minio'
[2024-09-25T11:07:53.822+0000] {base.py:84} INFO - Retrieving connection 'warehouse_db'
[2024-09-25T11:08:19.156+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-25T11:08:19.216+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T11:08:19.217+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=pipeline.warehouse.step_2.load.orderlines, run_id=manual__2024-09-25T11:02:00.229060+00:00, execution_date=20240925T110200, start_date=20240925T110752, end_date=20240925T110819
[2024-09-25T11:08:19.350+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-25T11:08:19.431+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-09-25T11:08:19.442+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
