[2024-09-25T11:06:09.925+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-09-25T11:06:09.990+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.init.create_bucket manual__2024-09-25T11:05:57.968197+00:00 [queued]>
[2024-09-25T11:06:10.020+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.init.create_bucket manual__2024-09-25T11:05:57.968197+00:00 [queued]>
[2024-09-25T11:06:10.020+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-09-25T11:06:10.061+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): init.create_bucket> on 2024-09-25 11:05:57.968197+00:00
[2024-09-25T11:06:10.080+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=488) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-09-25T11:06:10.083+0000] {standard_task_runner.py:72} INFO - Started process 491 to run task
[2024-09-25T11:06:10.087+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'init.create_bucket', 'manual__2024-09-25T11:05:57.968197+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline/run.py', '--cfg-path', '/tmp/tmp7lfhvfup']
[2024-09-25T11:06:10.093+0000] {standard_task_runner.py:105} INFO - Job 137: Subtask init.create_bucket
[2024-09-25T11:06:10.257+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.init.create_bucket manual__2024-09-25T11:05:57.968197+00:00 [running]> on host e10075799413
[2024-09-25T11:06:10.595+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='init.create_bucket' AIRFLOW_CTX_EXECUTION_DATE='2024-09-25T11:05:57.968197+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-09-25T11:05:57.968197+00:00'
[2024-09-25T11:06:10.598+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-09-25T11:06:10.648+0000] {base.py:84} INFO - Retrieving connection 'minio'
[2024-09-25T11:06:10.693+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-09-25T11:06:10.721+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-09-25T11:06:10.722+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_pipeline, task_id=init.create_bucket, run_id=manual__2024-09-25T11:05:57.968197+00:00, execution_date=20240925T110557, start_date=20240925T110609, end_date=20240925T110610
[2024-09-25T11:06:10.791+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-09-25T11:06:10.908+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-09-25T11:06:10.915+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
