[2024-10-03T07:18:41.427+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-03T07:18:41.455+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_pipeline.warehouse.step_1.extract_transform.categories scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2024-10-03T07:18:41.471+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_pipeline.warehouse.step_1.extract_transform.categories scheduled__2024-10-02T00:00:00+00:00 [queued]>
[2024-10-03T07:18:41.472+0000] {taskinstance.py:2865} INFO - Starting attempt 21 of 21
[2024-10-03T07:18:41.490+0000] {taskinstance.py:2888} INFO - Executing <Task(SparkSubmitOperator): warehouse.step_1.extract_transform.categories> on 2024-10-02 00:00:00+00:00
[2024-10-03T07:18:41.502+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_pipeline', 'warehouse.step_1.extract_transform.categories', 'scheduled__2024-10-02T00:00:00+00:00', '--job-id', '13562', '--raw', '--subdir', 'DAGS_FOLDER/etl_pipeline/run.py', '--cfg-path', '/tmp/tmpszjybig2']
[2024-10-03T07:18:41.506+0000] {standard_task_runner.py:105} INFO - Job 13562: Subtask warehouse.step_1.extract_transform.categories
[2024-10-03T07:18:41.511+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=28264) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-03T07:18:41.512+0000] {standard_task_runner.py:72} INFO - Started process 28266 to run task
[2024-10-03T07:18:41.587+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_pipeline.warehouse.step_1.extract_transform.categories scheduled__2024-10-02T00:00:00+00:00 [running]> on host 8c0d519f07a3
[2024-10-03T07:18:41.734+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_pipeline' AIRFLOW_CTX_TASK_ID='warehouse.step_1.extract_transform.categories' AIRFLOW_CTX_EXECUTION_DATE='2024-10-02T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='21' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-02T00:00:00+00:00'
[2024-10-03T07:18:41.736+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-03T07:18:41.756+0000] {base.py:84} INFO - Retrieving connection 'spark-conn'
[2024-10-03T07:18:41.757+0000] {spark_submit.py:335} INFO - Spark-Submit cmd: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories True 2024-10-02
[2024-10-03T07:18:41.818+0000] {spark_submit.py:488} INFO - /home/***/.local/lib/python3.12/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-10-03T07:18:50.216+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO SparkContext: Running Spark version 3.5.3
[2024-10-03T07:18:50.218+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO SparkContext: OS info Linux, 5.15.153.1-microsoft-standard-WSL2, amd64
[2024-10-03T07:18:50.219+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO SparkContext: Java version 17.0.12
[2024-10-03T07:18:50.304+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-10-03T07:18:50.458+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO ResourceUtils: ==============================================================
[2024-10-03T07:18:50.459+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-10-03T07:18:50.460+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO ResourceUtils: ==============================================================
[2024-10-03T07:18:50.461+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO SparkContext: Submitted application: Extract Transform - categories
[2024-10-03T07:18:50.494+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-10-03T07:18:50.509+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO ResourceProfile: Limiting resource is cpu
[2024-10-03T07:18:50.511+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-10-03T07:18:50.598+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO SecurityManager: Changing view acls to: ***
[2024-10-03T07:18:50.599+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO SecurityManager: Changing modify acls to: ***
[2024-10-03T07:18:50.601+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO SecurityManager: Changing view acls groups to:
[2024-10-03T07:18:50.603+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO SecurityManager: Changing modify acls groups to:
[2024-10-03T07:18:50.604+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:50 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-10-03T07:18:51.015+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO Utils: Successfully started service 'sparkDriver' on port 42727.
[2024-10-03T07:18:51.070+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO SparkEnv: Registering MapOutputTracker
[2024-10-03T07:18:51.147+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO SparkEnv: Registering BlockManagerMaster
[2024-10-03T07:18:51.203+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-10-03T07:18:51.207+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-10-03T07:18:51.217+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-10-03T07:18:51.277+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-4f0263cf-02e2-42ec-976c-c2b8c90e7e6d
[2024-10-03T07:18:51.317+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-10-03T07:18:51.346+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-10-03T07:18:51.542+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-10-03T07:18:51.637+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-10-03T07:18:51.901+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:51 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2024-10-03T07:18:52.025+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO TransportClientFactory: Successfully created connection to spark-master/172.20.0.2:7077 after 71 ms (0 ms spent in bootstraps)
[2024-10-03T07:18:52.234+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20241003071852-0018
[2024-10-03T07:18:52.237+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20241003071852-0018/0 on worker-20241003061731-172.20.0.9-38803 (172.20.0.9:38803) with 2 core(s)
[2024-10-03T07:18:52.244+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO StandaloneSchedulerBackend: Granted executor ID app-20241003071852-0018/0 on hostPort 172.20.0.9:38803 with 2 core(s), 1024.0 MiB RAM
[2024-10-03T07:18:52.251+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 33675.
[2024-10-03T07:18:52.252+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO NettyBlockTransferService: Server created on 8c0d519f07a3:33675
[2024-10-03T07:18:52.254+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-10-03T07:18:52.267+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 8c0d519f07a3, 33675, None)
[2024-10-03T07:18:52.274+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO BlockManagerMasterEndpoint: Registering block manager 8c0d519f07a3:33675 with 434.4 MiB RAM, BlockManagerId(driver, 8c0d519f07a3, 33675, None)
[2024-10-03T07:18:52.280+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 8c0d519f07a3, 33675, None)
[2024-10-03T07:18:52.284+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 8c0d519f07a3, 33675, None)
[2024-10-03T07:18:52.322+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20241003071852-0018/0 is now RUNNING
[2024-10-03T07:18:52.921+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:52 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-10-03T07:18:55.121+0000] {spark_submit.py:488} INFO - [2024-10-03T07:18:55.117+0000] {base.py:84} INFO - Retrieving connection 'staging_db'
[2024-10-03T07:18:55.146+0000] {spark_submit.py:488} INFO - Traceback (most recent call last):
[2024-10-03T07:18:55.147+0000] {spark_submit.py:488} INFO - File "/opt/***/dags/etl_pipeline/tasks/warehouse/components/extract_transform.py", line 58, in <module>
[2024-10-03T07:18:55.153+0000] {spark_submit.py:488} INFO - ExtractTransform._categories(incremental, date)
[2024-10-03T07:18:55.155+0000] {spark_submit.py:488} INFO - File "/opt/***/dags/etl_pipeline/tasks/warehouse/components/extract_transform.py", line 44, in _categories
[2024-10-03T07:18:55.156+0000] {spark_submit.py:488} INFO - raise e
[2024-10-03T07:18:55.158+0000] {spark_submit.py:488} INFO - File "/opt/***/dags/etl_pipeline/tasks/warehouse/components/extract_transform.py", line 30, in _categories
[2024-10-03T07:18:55.159+0000] {spark_submit.py:488} INFO - raise AirflowSkipException("categories doesn't have new data. Skipped...")
[2024-10-03T07:18:55.161+0000] {spark_submit.py:488} INFO - ***.exceptions.AirflowSkipException: categories doesn't have new data. Skipped...
[2024-10-03T07:18:55.162+0000] {spark_submit.py:488} INFO - [2024-10-03T07:18:55.149+0000] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-10-03T07:18:56.150+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO SparkContext: Invoking stop() from shutdown hook
[2024-10-03T07:18:56.152+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2024-10-03T07:18:56.178+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO SparkUI: Stopped Spark web UI at http://8c0d519f07a3:4040
[2024-10-03T07:18:56.189+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO StandaloneSchedulerBackend: Shutting down all executors
[2024-10-03T07:18:56.199+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2024-10-03T07:18:56.247+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2024-10-03T07:18:56.288+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO MemoryStore: MemoryStore cleared
[2024-10-03T07:18:56.293+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO BlockManager: BlockManager stopped
[2024-10-03T07:18:56.308+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO BlockManagerMaster: BlockManagerMaster stopped
[2024-10-03T07:18:56.312+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2024-10-03T07:18:56.332+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO SparkContext: Successfully stopped SparkContext
[2024-10-03T07:18:56.333+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO ShutdownHookManager: Shutdown hook called
[2024-10-03T07:18:56.336+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO ShutdownHookManager: Deleting directory /tmp/spark-96f58848-f672-4ad2-b5bd-818f5d2c7a4c
[2024-10-03T07:18:56.341+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO ShutdownHookManager: Deleting directory /tmp/spark-87d5c773-bb05-4f46-af52-3f9c87610455
[2024-10-03T07:18:56.346+0000] {spark_submit.py:488} INFO - 24/10/03 07:18:56 INFO ShutdownHookManager: Deleting directory /tmp/spark-96f58848-f672-4ad2-b5bd-818f5d2c7a4c/pyspark-cd4c29b4-0155-4014-a73e-84b8dd6fe09c
[2024-10-03T07:18:56.413+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories True 2024-10-02. Error code is: 1.
[2024-10-03T07:18:56.420+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=etl_pipeline, task_id=warehouse.step_1.extract_transform.categories, run_id=scheduled__2024-10-02T00:00:00+00:00, execution_date=20241002T000000, start_date=20241003T071841, end_date=20241003T071856
[2024-10-03T07:18:56.420+0000] {taskinstance.py:1563} INFO - Executing callback at index 0: slack_notifier
[2024-10-03T07:18:56.424+0000] {baseoperator.py:405} WARNING - SlackWebhookOperator.execute cannot be called outside TaskInstance!
[2024-10-03T07:18:56.435+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/providers/slack/hooks/slack_webhook.py:42 UserWarning: You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration. See: https://api.slack.com/messaging/webhooks#advanced_message_formatting. It is possible to change this values only in Legacy Slack Integration Incoming Webhook: https://api.slack.com/legacy/custom-integrations/messaging/webhooks#legacy-customizations
[2024-10-03T07:18:56.457+0000] {base.py:84} INFO - Retrieving connection 'slack_notifier'
[2024-10-03T07:18:56.566+0000] {client.py:219} ERROR - Failed to send a request to Slack API server: <urlopen error [Errno -3] Temporary failure in name resolution>
[2024-10-03T07:18:56.567+0000] {client.py:231} INFO - A retry handler found: ConnectionErrorRetryHandler for POST *** - <urlopen error [Errno -3] Temporary failure in name resolution>
[2024-10-03T07:18:57.802+0000] {client.py:240} INFO - Going to retry the same request: POST ***
[2024-10-03T07:18:57.811+0000] {client.py:219} ERROR - Failed to send a request to Slack API server: <urlopen error [Errno -3] Temporary failure in name resolution>
[2024-10-03T07:18:57.811+0000] {taskinstance.py:1567} ERROR - Error in callback at index 0: slack_notifier
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories True 2024-10-02. Error code is: 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/urllib/request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/usr/local/lib/python3.12/http/client.py", line 1470, in connect
    super().connect()
  File "/usr/local/lib/python3.12/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 841, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/socket.py", line 976, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 1565, in _run_finished_callback
    callback(context)
  File "/opt/airflow/dags/helper/callbacks/slack_notifier.py", line 28, in slack_notifier
    slack_webhook_task.execute(context=context)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/operators/slack_webhook.py", line 112, in execute
    self.hook.send(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 249, in send
    return self.send_dict(body=body, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 42, in wrapper
    resp = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/slack/hooks/slack_webhook.py", line 206, in send_dict
    return self.client.send_dict(body, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/slack_sdk/webhook/client.py", line 137, in send_dict
    return self._perform_http_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/slack_sdk/webhook/client.py", line 244, in _perform_http_request
    raise err
  File "/home/airflow/.local/lib/python3.12/site-packages/slack_sdk/webhook/client.py", line 164, in _perform_http_request
    resp = self._perform_http_request_internal(url, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/slack_sdk/webhook/client.py", line 270, in _perform_http_request_internal
    http_resp = urlopen(req, context=self.ssl, timeout=self.timeout)  # skipcq: BAN-B310
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/urllib/request.py", line 1347, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -3] Temporary failure in name resolution>
[2024-10-03T07:18:57.837+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-03T07:18:57.839+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 13562 for task warehouse.step_1.extract_transform.categories (Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories True 2024-10-02. Error code is: 1.; 28266)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 157, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 419, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://spark-master:7077 --name arrow-spark dags/etl_pipeline/tasks/warehouse/components/extract_transform.py categories True 2024-10-02. Error code is: 1.
[2024-10-03T07:18:57.864+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-03T07:18:57.887+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-03T07:18:57.891+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
